### ISSUE TITLE
GPL versus MIT license

### ISSUE THREAD

**Issue by stevenmhunt** [sytac/gulp-commonjs-tasks#6]
Do you have a particular intention in mind by licensing your NPM module under GPLv3? The legal implications of GPL on a JavaScript library have never been tested in a court of law, but I would still be hesitant to depend on your module just in case there was a chance it would trigger a viral license on any proprietary code I had running through the build system. You may want to consider the more community standard MIT license, which is more permissive.

**Comment by jpwesselink** [comment]
Point taken, let me fix that.

**Comment by jpwesselink** [comment]
Thanks for pointing it out, MIT it is.
