### ISSUE TITLE
Is this needed?

### ISSUE THREAD

**Issue by yocontra** [sytac/gulp-commonjs-tasks#7]
What is this module doing that you can't do with gulp 4? Curious to see where we failed.

**Comment by yocontra** [comment]
FYI in all version of gulp this works just fine:

``` js
gulp.task('some-thing', require('./tasks/some-thing'))
```

and this

``` js
var tasks = require('require-dir')('./tasks');

Object.keys(tasks).forEach(function(k){
  gulp.task(k, tasks[k]);
});
```

**Comment by yocontra** [comment]
In 4.0 we added the ability to do this (takes the function name)

``` js
gulp.task(require('./tasks/some-thing'));
```

and the second example could change to

``` js
var tasks = require('require-dir')('./tasks');

Object.keys(tasks).forEach(function(k){
  gulp.task(tasks[k]);
});
```

**Comment by jpwesselink** [comment]
There's no failing from your side whatsoever. This project started out as a convenience layer on top of gulp 3. I am well aware that some functionality will become obsolete when gulp 4 lands. Right now my time is limited, so I don't have much time to reply, but let's find out if we really need this.
