### ISSUE TITLE
Can't seem to get the system running

### ISSUE THREAD

**Issue by Industrial** [sytac/gulp-commonjs-tasks#8]
Hi!

I've been a bit too enthousiastic in converting my gulpfile to this module based approach. I've left it in a non-working state ..

The goal of my `id-builder` module is to publish my gulp setup as a NPM module that is configurable with an options object so I can just change a few paths between projects and expect to be developing in the same way without having to copy over gulp code between projects. This project goes way back and is now in it's fourth incarnation :-D

I'm using ES6 to write the gulp source and run it with `babel-core/register` from the gulpfie; https://github.com/Industrial/id-builder/blob/master/gulpfile.js#L7

This runs this function: https://github.com/Industrial/id-builder/blob/master/src/index.js#L7

I've added `lazy: false` to look inside the plugins to see they all actually load. I believe it's not needed (yay lazy? not really sure why this is loaded lazily .. i actually use all the plugins ..) but it kept giving me an empty object without; https://github.com/Industrial/id-builder/blob/master/src/index.js#L8

The debugger gets to the end of this function fine but it seems no plugins are actually loaded.

This is the output;

```
[00:28:41] Using gulpfile ~/Code/id-builder/gulpfile.js
[00:28:41] Starting 'help'...
help Usage
  gulp task [ option ... ]
Tasks
  help   : Show help
    -a, --all   : Also show tasks without descriptions 
[00:28:41] Finished 'help' after 1.87 ms
[00:28:41] Starting 'default'...
```

Any idea what's wrong here?

Cheers!

**Comment by jpwesselink** [comment]
Tom, give me a call tomorrow and we'll sort this straight away : )
